# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestiOSCeiba' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestiOSCeiba
  pod 'Alamofire'

  target 'TestiOSCeibaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestiOSCeibaUITests' do
    # Pods for testing
  end

end
